# Generated by Django 4.2.11 on 2025-05-21 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
