# Generated by Django 4.2.11 on 2025-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0003_alter_estacao_altitude_alter_estacao_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
