# Generated by Django 4.2.11 on 2025-09-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0004_alter_estacao_altitude_alter_estacao_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estacao',
            table='simc_estacao',
        ),
    ]
