# Generated by Django 4.2.11 on 2025-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0005_alter_estacao_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='identificador',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
