# Generated by Django 4.2.11 on 2025-10-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicao', '0006_rename_chuva_medicao_direcao_vento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-triangle-exclamation', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='medicao.medicao')),
            ],
            options={
                'db_table': 'simc_notificacao',
                'ordering': ['-timestamp'],
            },
        ),
    ]
