# Generated by Django 4.2.11 on 2025-07-25 05:11

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', account.managers.UsuarioManager()),
            ],
        ),
    ]
