# Generated by Django 4.2.11 on 2025-07-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contato',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
