# Generated by Django 4.2.11 on 2025-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usuario_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_Token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
