# Generated by Django 4.2.11 on 2025-09-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usuario_senha_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endereco',
            table='simc_endereco',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='simc_usuario',
        ),
    ]
