# Generated by Django 4.2.11 on 2025-05-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0004_remove_medicao_velocidade_vento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='qualidade_ar',
        ),
    ]
