# Generated by Django 4.2.11 on 2025-09-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0005_remove_medicao_qualidade_ar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicao',
            old_name='chuva',
            new_name='direcao_vento',
        ),
        migrations.AddField(
            model_name='medicao',
            name='pluviometro',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicao',
            name='velocidade_vento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='medicao',
            table='simc_medicao',
        ),
    ]
