# Generated by Django 4.2.11 on 2024-10-18 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('idMedicao', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('umidade_ar', models.FloatField()),
                ('umidade_solo', models.FloatField()),
                ('luminosidade', models.FloatField()),
                ('chuva', models.FloatField()),
                ('qualidade_ar', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('idEstacao_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacao.estacao')),
            ],
        ),
    ]
