# Generated by Django 4.2.11 on 2025-03-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicao',
            table='flu_medicao',
        ),
    ]
