# Generated by Django 4.2.11 on 2025-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicao',
            old_name='qualidade_ar',
            new_name='uv',
        ),
        migrations.AddField(
            model_name='medicao',
            name='velocidade_vento',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
