# Generated by Django 4.2.11 on 2025-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0002_rename_qualidade_ar_medicao_uv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='qualidade_ar',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
