# Generated by Django 4.2.11 on 2025-04-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0002_alter_medicao_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicao',
            old_name='idMedicao',
            new_name='id',
        ),
    ]
