# Generated by Django 4.2.11 on 2025-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0003_rename_idmedicao_medicao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='uv',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
