# Generated by Django 4.2.11 on 2025-05-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0003_medicao_qualidade_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='velocidade_vento',
        ),
    ]
