# Generated by Django 4.2.11 on 2025-05-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0004_medicao_uv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='qualidade_ar',
        ),
    ]
