# Generated by Django 4.2.11 on 2025-03-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estacao',
            table='flu_estacao',
        ),
    ]
