# Generated by Django 4.2.11 on 2025-05-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0002_alter_estacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='altitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='status_boolean',
            field=models.BooleanField(default=True),
        ),
    ]
